name: 'Extended Hugo Action'
description: 'Hugo extended, with Asciidoctor, PlantUML and other support'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.destination }}
